name: CI

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:18
                env:
                    POSTGRES_USER: test
                    POSTGRES_PASSWORD: test
                    POSTGRES_DB: kr_test

                ports:
                    - 5432:5432

                options: >-
                    --health-cmd "pg_isready -U test -d kr_test"
                    --health-interval 5s
                    --health-timeout 5s
                    --health-retries 10

        env:
            NODE_ENV: test
            DATABASE_URL: postgresql://test:test@localhost:5432/kr_test

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Set up Docker Compose
              run: docker compose version

            - name: Generate Prisma Client
              run: pnpm prisma generate

            - name: Run migrations
              run: pnpm prisma migrate deploy

            - name: Typecheck
              run: pnpm typecheck

            - name: Run tests
              run: pnpm test
